name: Pokemon map

on:
  workflow_dispatch:
  schedule: [{ cron: "0 23 * * 0" }]

permissions:
  contents: write

jobs:
  gracidea:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Capture Gracidea live map
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.gracidea.svg
          base: ""
          template: classic
          plugin_screenshot: yes
          plugin_screenshot_title: "Gracidea - a Pokemon live map by @lowlighter"
          plugin_screenshot_url: https://gracidea.lecoq.io/
          plugin_screenshot_selector: canvas
          plugin_screenshot_mode: image
          plugin_screenshot_background: yes
          plugin_screenshot_wait: 15000
          plugin_screenshot_viewport: |
            {"width": 1000, "height": 480}
